#%RAML 0.8
title: My Kvstore
baseUri: http://kvstoretest-fischmiskvstore.apps.opsv3.cloudcomplab.ch/
version: v1
protocols: [ HTTP ]
mediaType: application/html
documentation:
  - title: KV Store Documentation
    content: !include README.md
